name: Download and Upload

on:
  workflow_dispatch:
    inputs:
       User_Agent:
        type: string
        description: User-Agent
        required: true
        default: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
       Referer:
        type: string
        description: Referer
        required: true
        default: "https://github.com/"
       Download_URL:
        type: string
        description: Download URL
        required: true
        default: ""
       File_name:
        type: string
        description: File Name
        required: true
        default: ""
       Release_name:
        type: string
        description: Release name
        required: true
        default: ""
       Tag_name:
        type: string
        description: Tag name
        required: true
        default: ""
    

jobs:
  Download-Upload:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: Download file
        run: |
         sudo apt-get update
         sudo apt-get install aria2 rar python3 -y
         aria2c --dir="/tmp/downloaded-file" --out="${{ inputs.File_name }}" –-referer="${{ inputs.Referer }}" --user-agent="${{ inputs.User_Agent }}" --max-tries=0 --continue=true --max-connection-per-server=16 --split=64 "${{ inputs.Download_URL }}"
 
  #    - name: Upload artifact
  #      uses: actions/upload-artifact@main
  #      with:
  #        name: ${{ inputs.Release_name }}
  #        path: /tmp/downloaded-file/
  
      - name: Create Release and Upload Release Asset
        uses: ncipollo/release-action@main
        with:
          artifacts: |
            /tmp/downloaded-file/*
          name: "${{ inputs.Release_name }}"
          body: "${{ inputs.Release_name }}"
          tag: "${{ inputs.Tag_name }}"
          allowUpdates: true
          artifactErrorsFailBuild: true
          prerelease: true
          token: ${{ secrets.PAT }}

  # Delete:
  #   needs: [Download,Upload]
  #   runs-on: ubuntu-latest
  #   # runs-on: self-hosted
  #   steps:
  #     - name: Delete old file
  #       run: |
  #        rm -rf /tmp/downloaded-file/*

  Delete-old-workflow-run:
    needs: [Download-Upload]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - name: Delete old workflow run using Personal Token
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
